### ISSUE TITLE
Consider relaxing forbidden odd dimensions of subsampled chroma grid images

### ISSUE THREAD

**Issue by y-guyon** [MPEGGroup/MIAF#11]
ISO 23000-22:2019, section 7.3.11.4.2 Grid tile size:

> The tile size is restricted according to the chroma sampling format of the input images; the cropping shall select an integer number of samples for all planes, and result in an output image that also includes an integer number of samples for all planes. In effect, this means that:
> - when the images are in the 4:4:4 or 4:0:0 chroma sampling format, there is no restriction;
> - when the images are in the 4:2:2 chroma sampling format the horizontal tile offsets and widths, **and the output width,** shall be even numbers;
> - when the images are in the 4:2:0 chroma sampling format both the horizontal and vertical tile offsets and widths, **and the output width and height,** shall be even numbers.

The consequence of the above rules is that a 4:2:0 grid image of 123 by 123 pixels (with `tile_width` and `tile_height` being 64) is forbidden, while 124 by 124 is allowed. I did not find similar constraints on non-grid images. It seems unreasonable to forbid an image solely because of the presence of a grid.

**I suggest removing the constraints on output dimensions while keeping the constraints on tile offsets and dimensions.** The right-most pixel column and bottom-most pixel row of the reconstructed image can be taken from the right-most and bottom-most tiles, no matter that the reconstructed image dimensions are odd or even.

Note: Constraints on tile dimensions are important, otherwise it could lead to pixels in tiles that do not fit in the reconstructed image. [See example here.](https://github.com/AOMediaCodec/libavif/pull/834/files#diff-ec1e83a30f404fafbe1e20f72e829cf6a15a13fea594549f028dd489d37ff6bbR746)

Context: I am investigating how to implement incremental decoding in libavif and would like to use grid images, but it is currently impossible for 4:2:0 images with odd dimensions without using a `CleanApertureBox`.

**Comment by leo-barnes** [comment]
My memory is kind of hazy, but I think the general idea was to simply not allow odd dimensions at all for subsampled images since our experience indicated that many implementations simply didn't seem to handle it very well. If you look at `7.3.6.7 Clean aperture, rotation and mirror`, it also disallows odd `clap` offsets and sizes for subsampled images.

The intention back then was to make MIAF a subset of HEIF that was guaranteed to work well everywhere. You could always fall back to using the full HEIF spec for everything else, but with less guarantees that you would have good portability.

This was before AVIF existed though, and given that AVIF is based on MIAF rather than HEIF, I guess it also inherits those restrictions.

**Comment by y-guyon** [comment]
Thank you for the explanation. I searched for occurrences of "odd", "even" or "multiple of 2" in all AVIF-related specifications:

- MIAF 7.3.11.4 `grid`
- MIAF 7.3.6.7 `clap`
- AV1 nothing
- AVIF nothing
- HEIF nothing
- ISOBMFF nothing

So the discussion can be tied to MIAF and AVIF unless I missed something.

> the general idea was to simply not allow odd dimensions at all for subsampled images

Why cannot I find it specified except for `grid` and `clap` then?

What would be your suggested way forward:

1. Allow "`grid` odd 4:2:0" in MIAF because "odd 4:2:0" is not forbidden anyway (what I initially requested)
2. Forbid "odd 4:2:0" (not just `grid` or `clap` but any image) in MIAF for consistency
3. Forbid "odd 4:2:0" (not just `grid` or `clap` but any image) in AVIF specification for consistency
4. Refuse to encode "odd 4:2:0" in AVIF implementation (libavif, libheif) but allow decoding it (no spec change)
5. Keep the current asymmetric `grid`/no-`grid` behavior (no spec change)

Here are a few use cases that would justify 1. according to me:

- AVIF Photoshop plug-in error prompt: "The current encoding settings are forbidden. Please use even dimensions, disable chroma downsampling or disable incremental decoding."
- Server-side on-the-fly transcoding: [conversion failed because incremental odd 4:2:0]

**Comment by leo-barnes** [comment]
> Allow "grid odd 4:2:0" in MIAF because "odd 4:2:0" is not forbidden anyway (what I initially requested)

Back when MIAF was first created AVC and HEVC were basically the only two codecs considered. If I remember correctly, neither of those codecs allow for odd dimensions and subsampling. So there was no need to forbid it at the container level since it simply couldn't be done at the codec level. 

I *thought* the same was true for AV1, but I may definitely be mistaken. Do you know how AV1 handles odd dimensions and subsampling? If AV1 does support odd dimensions and subsampling, I agree that the 'grid' output size restrictions seem strange.

I'm not completely sure what you mean by incremental decoding. I'm assuming you mean 'grid' images (which can be used to incrementally decode an image in tiles)?

Some comments on your use-cases:
> AVIF Photoshop plug-in error prompt: "The current encoding settings are forbidden. Please use even dimensions, disable chroma downsampling or disable incremental decoding"

If AV1 _does_ support odd dimensions, I can see why it ends up being a weird choice since not doing a 'grid' would allow you to do odd dimensions and use subsampling. But if it doesn't, I think the choices make sense given that we've seen subsampling cause all sorts of issues when combined with odd dimensions when you start involving hardware.

> Server-side on-the-fly transcoding: [conversion failed because incremental odd 4:2:0]

If you're transcoding to 4:2:0, the most logical source image is probably a 4:2:0 JPEG. But 4:2:0 JPEGs have center-center chroma siting, which is (currently) not supported in AV1. So you need to resample chroma in any case to do a correct transcode. Going back to 4:2:0 feels like it will drop even more information.

------------

All in all, I think it may make sense to revisit the restrictions, especially since they now apply to AVIF as well, and AVIF can't fall back to HEIF.

**Comment by dwsinger** [comment]
I think the observation was that many systems fail to handle 'pixel selection' when it falls in the middle of a sub-sampling block, either the explicit cropping of clap or the implicit cropping in grids. I don't think this is codec-related; it's about what happens post-codec and on the way to display.

**Comment by y-guyon** [comment]
> I'm not completely sure what you mean by incremental decoding. I'm assuming you mean 'grid' images (which can be used to incrementally decode an image in tiles)?

Yes. See the "Context" in my initial post. Sorry if that was not clear.

> Do you know how AV1 handles odd dimensions and subsampling?

In [libavif](https://github.com/AOMediaCodec/libavif/search?q=chromaShiftX) the downsampled plane dimensions are rounded up. \
In [AV1 specification](https://aomediacodec.github.io/av1-spec/#intermediate-output-preparation-process) the rounding is up. \
~In [dav1d](https://github.com/videolan/dav1d/blob/2131a2cdaf5d14495ff7f26c0f40232cacdfa561/src/picture.c#L55) the rounding seems down.~ ERRATUM: the rounding is up

### avifenc

```
avifenc odd.png -y 420 -o odd.avif && \
avifdec odd.avif --info
```
gives
```
Image decoded: odd.avif
 * Resolution     : 1019x677
 * Bit Depth      : 8
 * Format         : YUV420
 * Chroma Sam. Pos: 0
```
ComplianceWarden, version v29-master-rev4-g7e371b8 did not find any error with `odd.avif`.

### heif-enc

The [`--even-size` flag](https://github.com/strukturag/libheif/blob/0082fea96ee70a20c8906a0373bedec0c01777bc/examples/heif_enc.cc#L137) to crop images to even dimensions is also marked as `[deprecated]`.

```
heif-enc odd.png -o odd_heif.avif --avif -p chroma=420
heif-info odd_heif.avif -d
```
gives
```
MIME type: image/avif
| | | image width: 1019
| | | image height: 677
| | | chroma_subsampling_x: 1
| | | chroma_subsampling_y: 1
```

**Comment by leo-barnes** [comment]
@y-guyon 
> ### avifenc
> ```
> avifenc odd.png -y 420 -o odd.avif && \
> ```
Do you mind sharing this file so I can take a closer look at it? It's always easier to dig into concrete examples. 😊

**Comment by wantehchang** [comment]
I confirm that AV1 supports odd dimensions and chroma subsampling. You can verify that by searching for `(w + subX) >> subX` and `(h + subY) >> subY` in the AV1 specification. In particular, see the description of the arrays `OutU` and `OutV` in Section 7.18.2 on page 337.

Allowing the `output_width` and `output_height` of an image grid to be odd numbers when the image is in the 4:2:2 or 4:2:0 chroma sampling format is similar to the proposed change in https://github.com/MPEGGroup/MIAF/issues/8 to allow `cleanApertureWidth` and `cleanApertureHeight` to be odd numbers when the image is 4:2:2 or 4:2:0.

**Comment by leo-barnes** [comment]
@wantehchang 
Thanks for the confirmation.

@y-guyon 
> In [libavif](https://github.com/AOMediaCodec/libavif/search?q=chromaShiftX) the downsampled plane dimensions are rounded up.
In [AV1 specification](https://aomediacodec.github.io/av1-spec/#intermediate-output-preparation-process) the rounding is up.
In [dav1d](https://github.com/videolan/dav1d/blob/2131a2cdaf5d14495ff7f26c0f40232cacdfa561/src/picture.c#L55) the rounding seems down.

How come dav1d rounds down while the AV1 spec and libavif says to round up? Is that a bug in dav1d? If not, what does it mean in practice when decoding an odd-sized 4:2:0 image with dav1d? Issues like these were precisely why the restrictions were added to MIAF.

---

Like @dwsinger said, the restrictions were added due to having seen issues in general for subsampled images with odd dimensions, not only in the codec, but in general handling of them. If we want MIAF to maintain its original purpose as a spec for improving portability and codifying best practices, I think the restrictions make perfect sense and should remain as is. 
(And we should probably add some wording to also restrict subsampled odd-sized non-grid/clap images for codecs that support this.)

If AVIF wants to go against those restrictions, it should really be based on HEIF rather than MIAF. The MIAF brands can still be used when you want maximum portability.

**Comment by y-guyon** [comment]
> Do you mind sharing this file so I can take a closer look at it?

Any image with odd dimensions will do but sure. The archive contains `odd_encoded_with_libavif.avif` and `odd_encoded_with_libheif.avif` that cannot be sent through GitHub.
[odd.zip](https://github.com/MPEGGroup/MIAF/files/8040301/odd.zip)
[odd.png](https://user-images.githubusercontent.com/51164219/153390608-0f8fe185-27f8-4a55-935f-d8f7af949b16.png)

**Comment by wantehchang** [comment]
I was also confused to hear that "In [dav1d](https://github.com/videolan/dav1d/blob/2131a2cdaf5d14495ff7f26c0f40232cacdfa561/src/picture.c#L55) the rounding seems down." Here is the dav1d code snippet that Yannis linked to:

```
    ptrdiff_t uv_stride = has_chroma ? y_stride >> ss_hor : 0;
```

This code deals with the stride, not the width. The stride is padded to a multiple of at least 16 so that the beginning of each row is aligned. So y_stride is an even number. This is why we can just write `y_stride >> ss_hor` as opposed to `(y_stride + ss_hor) >> ss_hor`.

Although I did not inspect the code, I am confident that dav1d handles odd widths and heights according to the AV1 spec.

**Comment by leo-barnes** [comment]
@wantehchang 
> Although I did not inspect the code, I am confident that dav1d handles odd widths and heights according to the AV1 spec.

Thanks for checking, would have been very surprising if it did not adhere to the spec, but I've seen stranger decisions before 🙂

**Comment by y-guyon** [comment]
> I am confident that dav1d handles odd widths and heights according to the AV1 spec.

Sorry for the confusion. I tried to quickly look the behaviors of several sources up but did not investigate enough.

I extracted the OBU payload of [odd_encoded_with_libavif.avif](https://github.com/MPEGGroup/MIAF/issues/11#issuecomment-1034764212) and decoded it with `dav1d` and `aomdec`. Besides the y4m header (`W123 H123 C420`), the files are identical. The pixels take 22 817 bytes, corresponding to 123×123px + 2×62×62px, matching the "round up" behavior. \
VQAnalyzer corroborates this by only showing 123×123 pixels and "cropping in half" chroma samples zoomed ×2. The "picture boundary" layer seems aligned with 128px, as in dav1d code.

If necessary I can also verify libgav1 and all AV1/AVIF codecs, but let's consider they all have the same behavior on that "odd 4:2:0" matter. What else would be needed before proceeding with the original request?

**Comment by leo-barnes** [comment]
Accepted into Amendment 2.

New text:
```
—	when the images are in the 4:4:4 or 4:0:0 chroma sampling format, there is no restriction;
—	when the images are in the 4:2:2 chroma sampling format, the horizontal tile offsets and tile widths shall be even numbers;
—	when the images are in the 4:2:0 chroma sampling format, both the horizontal and vertical tile offsets and tile widths and heights shall be even numbers.
```

**Comment by leo-barnes** [comment]
@cconcolato Can't seem to close the issue for some reason.
